# Generated by Django 2.2.11 on 2020-05-09 12:37

from django.db import migrations, models
import djongo.models.fields
import filters_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=filters_app.models.Blog, model_form_class=filters_app.models.BlogForm, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
